"""Generate data and method pipeline scaffolds from analyzed references."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Optional


def _safe_comment(text: str, limit: int = 1000) -> str:
    text = re.sub(r'\s+', ' ', text or '').strip()
    return text[:limit]


def _detect_capabilities(items: list[dict[str, Any]]) -> dict[str, bool]:
    parts = []
    for item in items:
        parts.extend(
            [
            item.get('title', ''),
            item.get('abstract', ''),
            (item.get('deep_summary') or {}).get('data_used', ''),
            (item.get('deep_summary') or {}).get('methods', ''),
            ]
        )
    blob = ' '.join(parts).lower()
    return {
        'remote_sensing': any(term in blob for term in ['sentinel', 'satellite', 'remote sensing', 'multispectral', 'hyperspectral']),
        'uav': any(term in blob for term in ['uav', 'drone']),
        'astronomy': any(term in blob for term in ['agn', 'active galactic', 'lsst', 'lamost', 'einstein probe', 'fits', 'light curve', 'spectra', 'quasar']),
        'image_dl': any(term in blob for term in ['cnn', 'resnet', 'efficientnet', 'image', 'leaf']),
        'transformer': any(term in blob for term in ['transformer', 'vit', 'attention']),
        'temporal': any(term in blob for term in ['lstm', 'time series', 'temporal', 'season', 'time-domain', 'light curve']),
        'classical_ml': any(term in blob for term in ['svm', 'random forest', 'xgboost', 'classification']),
    }


def generate_pipeline_files(
    *,
    request: Any,
    items: list[dict[str, Any]],
    cross_synthesis: dict[str, str],
    output_dir: Path,
    submission_id: str,
) -> dict[str, str]:
    """Write contextual demo_data/demo_method files and return file names."""
    output_dir.mkdir(parents=True, exist_ok=True)
    capabilities = _detect_capabilities(items)
    top_titles = [item.get('title', 'Untitled') for item in items[:8]]
    data_patterns = _safe_comment(cross_synthesis.get('data_patterns', ''))
    method_patterns = _safe_comment(cross_synthesis.get('method_patterns', ''))
    limitation_patterns = _safe_comment(cross_synthesis.get('limitation_patterns', ''))

    data_file = output_dir / f"demo_data_{submission_id}.py"
    method_file = output_dir / f"demo_method_{submission_id}.py"

    data_file.write_text(f'''"""Contextual data pipeline scaffold generated by ResearchDraft.ai.

Research topic:
{request.idea}

User data description:
{request.data_description or 'No user data description was provided.'}

Patterns extracted from highly weighted references:
{data_patterns}

Top references considered:
{chr(10).join(f'- {title}' for title in top_titles)}
"""

from __future__ import annotations

import numpy as np


def zscore(x: np.ndarray) -> np.ndarray:
    """Standardize a feature block while preserving missing values."""
    x = np.asarray(x, dtype=float)
    return (x - np.nanmean(x, axis=0, keepdims=True)) / (np.nanstd(x, axis=0, keepdims=True) + 1e-8)


def temporal_window_mean(series: np.ndarray, window: int = 3) -> np.ndarray:
    """Aggregate observations into rolling temporal windows."""
    series = np.asarray(series, dtype=float)
    output = []
    for idx in range(series.shape[0]):
        start = max(0, idx - window + 1)
        output.append(np.nanmean(series[start:idx + 1], axis=0))
    return np.stack(output, axis=0)


def quality_weighted_fusion(blocks: list[np.ndarray], quality: np.ndarray | None = None) -> np.ndarray:
    """Fuse multimodal feature blocks using source-quality weights."""
    normalized = [zscore(block) for block in blocks if block is not None]
    if quality is None:
        quality = np.ones(len(normalized), dtype=float)
    quality = np.asarray(quality, dtype=float)
    quality = quality / (quality.sum() + 1e-8)
    return np.concatenate([weight * block for weight, block in zip(quality, normalized)], axis=-1)


def build_multimodal_features(
    photometry_or_remote_sensing: np.ndarray | None = None,
    spectra_or_environment: np.ndarray | None = None,
    catalog_or_static_features: np.ndarray | None = None,
    image_features: np.ndarray | None = None,
    auxiliary_features: np.ndarray | None = None,
) -> np.ndarray:
    """Construct model-ready features from heterogeneous scientific data sources."""
    blocks = []
    if photometry_or_remote_sensing is not None:
        blocks.append(temporal_window_mean(photometry_or_remote_sensing))
    if spectra_or_environment is not None:
        blocks.append(temporal_window_mean(spectra_or_environment))
    if catalog_or_static_features is not None:
        blocks.append(catalog_or_static_features)
    if image_features is not None:
        blocks.append(image_features)
    if auxiliary_features is not None:
        blocks.append(auxiliary_features)
    if not blocks:
        raise ValueError("At least one data source must be provided.")
    return quality_weighted_fusion(blocks)


if __name__ == "__main__":
    demo = build_multimodal_features(
        photometry_or_remote_sensing=np.random.rand(8, 16),
        spectra_or_environment=np.random.rand(8, 6),
        catalog_or_static_features=np.random.rand(8, 4),
        image_features=np.random.rand(8, 12),
    )
    print("Demo feature matrix:", demo.shape)
''', encoding='utf-8')

    method_file.write_text(f'''"""Contextual multi-agent method scaffold generated by ResearchDraft.ai.

Research topic:
{request.idea}

Method patterns extracted from highly weighted references:
{method_patterns}

Shared limitations that the new method should address:
{limitation_patterns}
"""

from __future__ import annotations

import numpy as np


CAPABILITIES = {capabilities!r}


def softmax(logits: np.ndarray) -> np.ndarray:
    logits = np.asarray(logits, dtype=float)
    logits = logits - np.max(logits, axis=-1, keepdims=True)
    exp = np.exp(logits)
    return exp / (np.sum(exp, axis=-1, keepdims=True) + 1e-8)


def linear_agent(features: np.ndarray, weights: np.ndarray) -> np.ndarray:
    """A lightweight stand-in for a source-specific predictive agent."""
    return softmax(np.asarray(features) @ np.asarray(weights))


def reliability_from_validation(f1_scores: np.ndarray) -> np.ndarray:
    """Convert validation performance into agent-fusion weights."""
    scores = np.maximum(np.asarray(f1_scores, dtype=float), 1e-6)
    return scores / scores.sum()


def fuse_agent_outputs(agent_outputs: list[np.ndarray], reliability: np.ndarray) -> np.ndarray:
    """Fuse predictions from multiple data-source-specific agents."""
    reliability = reliability_from_validation(reliability)
    stacked = np.stack(agent_outputs, axis=0)
    return np.tensordot(reliability, stacked, axes=(0, 0))


def event_risk(probabilities: np.ndarray, event_class: int = 1) -> np.ndarray:
    """Return the event probability used for forecasting or early-warning outputs."""
    return np.asarray(probabilities)[..., event_class]


def temporal_risk_smoothing(risk: np.ndarray, alpha: float = 0.65) -> np.ndarray:
    """Smooth disease risk through the growing season."""
    risk = np.asarray(risk, dtype=float)
    output = np.zeros_like(risk)
    output[0] = risk[0]
    for idx in range(1, len(risk)):
        output[idx] = alpha * risk[idx] + (1 - alpha) * output[idx - 1]
    return output


if __name__ == "__main__":
    n, classes = 24, 2
    agent_outputs = [softmax(np.random.rand(n, classes)) for _ in range(4)]
    fused = fuse_agent_outputs(agent_outputs, np.array([0.82, 0.76, 0.68, 0.88]))
    print("Fused probability matrix:", fused.shape)
    print("Smoothed risk vector:", temporal_risk_smoothing(event_risk(fused)).shape)
''', encoding='utf-8')

    return {
        'demo_data': data_file.name,
        'demo_method': method_file.name,
    }
